---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: memelord-hirmus
spec:
  secretName: memelord-hirmus-tls
  dnsNames:
    - memelord-hirmus.ee-lte-1.codemowers.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memelord-hirmus
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: memelord-hirmus.ee-lte-1.codemowers.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: memelord
                port:
                  number: 80
  tls:
    - secretName: memelord-hirmus-tls

